### ISSUE TITLE
疑似スクリプトプラグインを書けるようにする

### ISSUE THREAD

**Issue by yuyaprgrm** [NeiroNetwork/EvalBook#17]
pmmpにはスクリプトプラグインがあり、一ファイルでそれ自体がプラグインとして動作します。
スクリプトプラグインファイルは以下の要素からなっています

- **ヘッダー** プラグインのメタデータ(description)の記述
- **ボディー** プラグインの実コードの記述

これと似たような仕組みをEvalBookでも実現することがこのIssueでの目的です。

実際に本に書き込む内容は以下のようなものです。
- **ヘッダー** プラグインのメタデータを記述する
```yml
# METADATA
type: file-base
parser-version: 0.1.4

# DESCRIPTION
name: EvalBookExamplePlugin
main: famima65536\departure\Main
version: 1.0.0
author: famima65536
```

- **ボディー** プラグインの実コードを記述
```php
# CODE
 namespace famima65536\departure;

use pocketmine\plugin\PluginBase;

class Main extends PluginBase{
    // code here
}
```

上にあるように #METADATA, #DESCRIPTION # CODE をファイルの区切りとして用います。
METADATAの記述がない場合には通常のEvalBookとしての実行されます。
